### ISSUE TITLE
I do not know what caused it  ...

### ISSUE THREAD

**Issue by llong0807** [luckyandyzhang/RetrofitLifecycle#1]
annotationProcessor 'com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle-compiler:1.0.0'

Failed to resolve: com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle:1.0.0
No more tips

------
 //annotationProcessor 'com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle-compiler:1.0.0'
 Is this superfluous,  ?   no it can run

**Comment by andydevacc** [comment]
> annotationProcessor 'com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle-compiler:1.0.0'
> 
> Failed to resolve: com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle:1.0.0
> No more tips
> 
> //annotationProcessor 'com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle-compiler:1.0.0'
> Is this superfluous, ? no it can run  

@llong0807  `'com.github.luckyandyzhang.RetrofitLifecycle:retrofit-lifecycle-compiler:1.0.0'` is needed by annotation processor to generate code.  

Did you forget to add `maven { url 'https://jitpack.io' } ` in your root `build.gradle` ? see  [Usage](https://github.com/luckyandyzhang/RetrofitLifecycle#usage)
