### ISSUE TITLE
cancelAll()还必须传参?

### ISSUE THREAD

**Issue by ruodezizaiyi** [luckyandyzhang/RetrofitLifecycle#2]
对多个请求是不是cancelAll()可以直接cancel掉mCallList的所有call?

**Comment by andydevacc** [comment]
> 对多个请求是不是cancelAll()可以直接cancel掉mCallList的所有call?

@ruodezizaiyi 是的，不传任何参数的话，默认会cancel掉所有的call。这个参数是可变参数，表示哪个请求不取消。

**Comment by ruodezizaiyi** [comment]
RetrofitLifecycle.cancelAll();

public static void cancelAll(Object retrofitAPI, Call... excludes) {
        if(retrofitAPI instanceof Cancellable) {
            ((Cancellable)retrofitAPI).cancelAll(excludes);
        } else {
            throw new IllegalArgumentException(retrofitAPI.getClass().getName() + " must implement Cancellable");
        }
    }
这儿必须要传一个retrofitAPI?

**Comment by andydevacc** [comment]
> RetrofitLifecycle.cancelAll();
> 
> public static void cancelAll(Object retrofitAPI, Call... excludes) {
> if(retrofitAPI instanceof Cancellable) {
> ((Cancellable)retrofitAPI).cancelAll(excludes);
> } else {
> throw new IllegalArgumentException(retrofitAPI.getClass().getName() + " must implement Cancellable");
> }
> }
> 这儿必须要传一个retrofitAPI?

@ruodezizaiyi 是的，考虑到可能有多个API Interface的存在。具体用法可以参考sample module
