### ISSUE TITLE
我在kotlin中使用 似乎有点问题

### ISSUE THREAD

**Issue by wogenhaosini** [luckyandyzhang/RetrofitLifecycle#3]
`companion object {

    val api:APIs

    init {
      val apiS = Retrofit.Builder()
          .baseUrl("http://baidu.com:8002/")
          .addConverterFactory(GsonConverterFactory.create())
          .client(DataLayer.okHttpClient)
          .build()
          .create(APIs::class.java)

      api = RetrofitLifecycle.getProxyInterface(APIs::class.java,apiS)
    }
  }`

会报错
`java.lang.ClassNotFoundException: packageName.HttpService$APIsInvokeProxy`

请指教

**Comment by andydevacc** [comment]
@wogenhaosini kotlin我不是很熟，貌似是annotationProcessor的问题，要换成kapt，可以根据官网的指引试一下 [传送门](https://kotlinlang.org/docs/reference/kapt.html)

**Comment by wogenhaosini** [comment]
@luckyandyzhang  是的  我改成用Kotlin-apt的形式了 但是使用过程中 NullPointerException  ApiInvokeProxy 中 mCallList 手动置为null？是为什么？ 方便留个联系方式吗？

**Comment by andydevacc** [comment]
@wogenhaosini 之前考虑到的场景是，cancelAll方法一般会在onDestroy的时候调用... 可能没考虑到特殊的使用场景，如果这样的话，确实不要设置为null好些。

**Comment by wogenhaosini** [comment]
@luckyandyzhang 对 我觉得直接复用一个应该是最好的。

**Comment by andydevacc** [comment]
@wogenhaosini 嗯，迟点解决这个问题  ：）
