### ISSUE TITLE
对于Retrofit回调对象的问题

### ISSUE THREAD

**Issue by MrsLi** [luckyandyzhang/RetrofitLifecycle#4]
对于Retrofit回调对象的问题是怎么处理的,这个只能用Call回调的吗?
如果Observable呢?

**Comment by andydevacc** [comment]
> 对于Retrofit回调对象的问题是怎么处理的,这个只能用Call回调的吗?
> 如果Observable呢?

@MrsLi 是的，只支持Call，对于Observable的话直接用RxLifecycle吧
